### PR TITLE
Fix overriding baseURL

### LINKED ISSUE #27: baseURL is being removed from ember
I've upgraded to latest beta version of ember-cli and latest ember.js and reload JS file returns 404 as baseURL is no more in the config.

### PR DESCRIPTION
**Pull request by jgoclawski**
Partially fixes #27 by allowing to override baseURL, which is being removed from ember-cli 2.7 (currently in beta).

### CODE REVIEW

**Comment by rwjblue** [comment]
This looks like a good refactor, but you mentioned that it only partially fixes things.  What are the remaining issues?

**Comment by jgoclawski** [comment]
Well, I think that this addon probably shouldn't use `baseURL` at all, right? I mean in the long run, as it's being deprecated and will eventually be removed from ember-cli.
http://emberjs.com/blog/2016/04/28/baseURL.html

This PR only allows to override it, which didn't fully work before :) My primary goal was to remove `baseURL` from my ember-cli config, which broke this addon.

**Comment by jgoclawski** [comment]
Hi, just a friendly ping. This commit is just a fix, so I think it can be easily merged and released.

The idea of not using `baseURL` at all should be a separate topic. Meanwhile this fix allows running live reload in Ember CLI 2.7 with custom rootURL (not equal to "/"). Otherwise it doesn't work.

**Comment by rwjblue** [comment]
Ya, this change looks good, but we need to figure out the root issue (pun intended).

**Comment by nathanhammond** [comment]
For `rootURL` this should be the end result that just works:

```javascript
// maintaining `baseURL` for backwards compatibility. See: http://emberjs.com/blog/2016/04/28/baseURL.html
var baseURL = options.liveReloadBaseUrl || options.rootURL || options.baseURL;
```

File: index.js [hunk 1]
```diff
@@ -28,13 +28,14 @@ module.exports = {
     var self = this;
     var app = config.app;
     var options = config.options;
+    var baseURL = options.liveReloadBaseUrl || options.baseURL;
```
Comment (rwjblue) [inline index.js]: Can you switch this to `options.liveReloadBaseUrl || options.rootURL || options.baseURL`?

**Comment by rwjblue** [comment]
Thanks for chiming in @nathanhammond.  One small tweak and we should be good here...

**Comment by jgoclawski** [comment]
Thanks for taking time to look into it. I've updated the PR according to your suggestions. There are 3 commit now, each clearly showing it's purpose.

**Comment by rwjblue** [comment]
Thank you!

**Comment by rwjblue** [comment]
Published

**Comment by jgoclawski** [comment]
Thanks!
